import Head from 'next/head';
import { Header } from 'src/components';

export default function Home() {
    return (
        <div className='relative h-screen'>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/logo.svg ' />
            </Head>
            <Header />
            <main></main>
        </div>
    );
}
